#!/usr/bin/env bash

set -x

case "$SNAP_ARCH" in
    "amd64") ARCH='x86_64-linux-gnu'
    ;;
    "i386") ARCH='i386-linux-gnu'
    ;;
    *)
        echo "Unsupported architecture for this app build"
        exit 1
    ;;
esac

VENDOR=$(glxinfo | grep "OpenGL vendor")

export VDPAU_DRIVER_PATH="$SNAP/usr/lib/$ARCH/vdpau"
export LIBVA_DRIVERS_PATH="$SNAP/usr/lib/$ARCH/dri"

if [[ $VENDOR == *"NVIDIA"* ]]; then
  export VDPAU_DRIVER_PATH="/var/lib/snapd/lib/gl/vdpau"
  # Prevent picking intel vaapi over nvidia vdpau (eg. on PRIME systems)
  unset LIBVA_DRIVERS_PATH
elif [[ $VENDOR == *"X.Org"* ]]; then
  export VDPAU_DRIVER_PATH="/usr/lib/$ARCH/vdpau/"
fi

exec "$@"
