name: moonlight
base: core18
adopt-info: moonlight-qt
grade: devel
confinement: strict
license: GPL-3.0+

apps:
  moonlight:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
  vainfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: vainfo
    plugs: *plugs
  vdpauinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: vdpauinfo
    plugs: *plugs
  glxinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: glxinfo
    plugs: *plugs

parts:
  va-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages: [mesa-utils, vainfo, vdpauinfo]

  moonlight-qt:
    plugin: qmake
    qt-version: qt5
    options: [PREFIX=/usr]
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-branch: master
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    override-build: |
      snapcraftctl set-version $(git describe --tags --long | sed "s/^v//")
      snapcraftctl build
    build-packages:
      - qtbase5-dev
      - qtquickcontrols2-5-dev
      - libqt5svg5-dev
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libxkbcommon-dev
      - wayland-protocols
      - libopus-dev
      - libva-dev
      - libvdpau-dev
      - libsdl2-dev
      - qtdeclarative5-dev
      - libssl-dev
      - libsdl2-ttf-dev
    stage-packages:
      - qml-module-qtquick2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qtwayland5
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - libvdpau-va-gl1
      - i965-va-driver
      - vdpau-va-driver
      - va-driver-all
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva-wayland2
      - libvdpau1
      - libasound2
      - libasyncns0
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libsndfile1
      - libsndio6.1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
    after:
      - desktop-qt5
      - ffmpeg

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-branch: sdk/8.1

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-branch: master
    configflags:
      - --prefix=/usr
      - --enable-pic
      - --enable-shared
      - --disable-static
      - --disable-all
      - --enable-avcodec
      - --enable-nvdec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_vdpau
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=hevc_nvdec
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
    after: [ffnvcodec]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make
