name: moonlight
base: core18
adopt-info: moonlight-qt
grade: devel
confinement: strict
license: GPL-3.0+
icon: moonlight.svg

apps:
  moonlight:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
  vainfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/vainfo
    plugs: *plugs
  vdpauinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/vdpauinfo
    plugs: *plugs
  eglinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/eglinfo
    plugs: *plugs
  glxinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/glxinfo
    plugs: *plugs

parts:
  va-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages: [mesa-utils, mesa-utils-extra, vainfo, vdpauinfo]

  moonlight-qt:
    plugin: qmake
    qt-version: qt5
    options: [PREFIX=/usr]
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-branch: master
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    override-build: |
      snapcraftctl set-version $(git describe --tags --long | sed "s/^v//")
      snapcraftctl build
    build-packages:
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libopus-dev
      - libqt5svg5-dev
      - libsdl2-ttf-dev
      - libssl-dev
      - libavcodec-dev
      - libva-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-default
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - libasound2
      - libasyncns0
      - libdrm2
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsdl2-ttf-2.0-0
      - libsndfile1
      - libsndio6.1
      - libva-drm2
      - libva-wayland2
      - libva-x11-2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all
    after:
      - desktop-qt5
      - ffmpeg
      - sdl2

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-branch: sdk/8.1

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-branch: master
    configflags:
      - --prefix=/usr
      - --enable-pic
      - --enable-shared
      - --disable-static
      - --disable-all
      - --enable-avcodec
      - --enable-nvdec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_vdpau
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=hevc_nvdec
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
    after: [ffnvcodec]

  sdl2:
    plugin: autotools
    source: https://www.libsdl.org/release/SDL2-2.0.12.tar.gz
    configflags:
      - --disable-rpath
      - --enable-sdl-dlopen
      - --disable-nas
      - --disable-esd
      - --disable-arts
      - --disable-alsa-shared
      - --disable-pulseaudio-shared
      - --enable-ibus
      - --disable-x11-shared
      - --disable-video-directfb
      - --enable-video-opengles
      - --enable-video-wayland
      - --disable-wayland-shared
      - --enable-video-mir
    build-packages:
      - fcitx-bin
      - fcitx-libs-dev
      - gir1.2-fcitx-1.0
      - libasound2-dev
      - libboost-filesystem1.65.1
      - libcapnp-0.6.1
      - libclang1-6.0
      - libdbus-1-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libfcitx-core0
      - libfcitx-qt0
      - libfile-stripnondeterminism-perl
      - libgettextpo0
      - libgl1-mesa-dev
      - libgles1
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libglib2.0-dev-bin
      - libglu1-mesa-dev
      - libglvnd-core-dev
      - libglvnd-dev
      - libibus-1.0-dev
      - libice-dev
      - libllvm6.0
      - libmirclient-dev
      - libmirclient9
      - libmircommon-dev
      - libmircommon7
      - libmircookie-dev
      - libmircookie2
      - libmircore-dev
      - libmircore1
      - libmirprotobuf3
      - libopengl0
      - libpcre16-3
      - libpcre3-dev
      - libpcre32-3
      - libpcrecpp0v5
      - libprotobuf-dev
      - libpthread-stubs0-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsm-dev
      - libsndio-dev
      - libtool
      - libudev-dev
      - libvulkan-dev
      - libwayland-bin
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxau-dev
      - libxcb-dri2-0-dev
      - libxcb-dri3-dev
      - libxcb-glx0-dev
      - libxcb-present-dev
      - libxcb-randr0-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-sync-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxdmcp-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxrender-dev
      - libxshmfence-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - mesa-common-dev
      - wayland-protocols
      - x11proto-core-dev
      - x11proto-damage-dev
      - x11proto-dev
      - x11proto-fixes-dev
      - x11proto-input-dev
      - x11proto-randr-dev
      - x11proto-scrnsaver-dev
      - x11proto-xext-dev
      - x11proto-xf86vidmode-dev
      - x11proto-xinerama-dev
      - xorg-sgml-doctools
      - xtrans-dev
      - zlib1g-dev

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make
    after: [kde-neon-ppa]

  kde-neon-ppa:
    plugin: nil
    override-pull: |
      echo "deb http://archive.neon.kde.org/release bionic main" | tee /etc/apt/sources.list.d/kde-neon.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E6D4736255751E5D
      apt update
      apt upgrade -yy
    build-packages:
      - dirmngr

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
      - va-wrapper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
    override-prime: |
      set -eux
      for snap in "core18"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
