name: moonlight
base: core22
adopt-info: moonlight-qt
grade: devel
confinement: strict
license: GPL-3.0+
icon: moonlight.svg
compression: lzo
summary: Stream games and apps from another PC running Sunshine or GeForce Experience

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 03F5D621A3710FA95A93D89BAA8452080E383F7E
    url: http://packages.lunarg.com/vulkan

environment:
  LIBDECOR_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor/plugins-1
  VK_ADD_DRIVER_FILES: /var/lib/snapd/lib/vulkan/icd.d:$SNAP/usr/share/vulkan/icd.d

apps:
  moonlight:
    command-chain: &command-chain
      - bin/desktop-launch
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
  vainfo:
    command-chain: *command-chain
    command: usr/bin/vainfo
    plugs: *plugs
  vdpauinfo:
    command-chain: *command-chain
    command: usr/bin/vdpauinfo
    plugs: *plugs
  eglinfo:
    command-chain: *command-chain
    command: usr/bin/eglinfo
    plugs: *plugs
  glxinfo:
    command-chain: *command-chain
    command: usr/bin/glxinfo
    plugs: *plugs
  vulkaninfo:
    command-chain: *command-chain
    command: usr/bin/vulkaninfo
    plugs: *plugs

parts:
  debugging:
    plugin: nil
    after:
      - libdecor
    build-packages:
      - vulkan-sdk
    stage-packages: [mesa-utils, mesa-utils-extra, vainfo, vdpauinfo, vulkan-tools]

  moonlight-qt:
    plugin: qmake
    qmake-major-version: 5
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-branch: master
    parse-info:
      - app/deploy/linux/com.moonlight_stream.Moonlight.appdata.xml
      - usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --long | sed "s/^v//")
    build-environment: &build-environment
      - CFLAGS: -O2 -g -pipe
      - CXXFLAGS: -O2 -g -pipe
    qmake-parameters:
      - CONFIG+=c++17
      - CONFIG+=disable-cuda
      - CONFIG+=disable-libdrm
      - QMAKE_LFLAGS+=-Wl,-rpath-link,${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${CRAFT_STAGE}/usr/lib  # Need to set rpath manually for the linker to find libdav1d
      - PREFIX=/usr
    after:
      - desktop-qt5
      - ffmpeg
      - libplacebo
      - libva
      - sdl
      - sdl-ttf
    build-packages:
      - libopus-dev
      - libqt5svg5-dev
      - libssl-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - vulkan-sdk
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - intel-media-va-driver-non-free
      - libasound2
      - libasyncns0
      - libdrm2
      - libegl1-mesa-dev
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsndfile1
      - libsndio7.0
      - libvdpau-va-gl1
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - mesa-vulkan-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all

  ffmpeg:
    plugin: autotools
    source: https://github.com/cgutman/FFmpeg.git
    source-branch: moonlight_8.0.1_r1
    source-depth: 1
    autotools-configure-parameters:
      - --fatal-warnings
      - --disable-stripping
      - --enable-pic
      - --enable-shared
      - --disable-static
      - --disable-all
      - --disable-v4l2-m2m
      - --disable-v4l2-request
      - --enable-avcodec
      - --enable-avformat
      - --enable-swscale
      - --enable-libdav1d
      - --enable-decoder=libdav1d
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-decoder=av1
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=av1_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_vdpau
      - --enable-hwaccel=h264_vulkan
      - --enable-hwaccel=hevc_vulkan
      - --enable-hwaccel=av1_vulkan
      - --prefix=/usr
    build-environment: *build-environment
    after:
      - dav1d
      - libva
      - sdl
    build-packages:
      - libvdpau-dev
      - libx265-dev
      - nasm
      - vulkan-sdk
    stage-packages:
      - libdrm2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3

  libva:
    plugin: autotools
    source: https://github.com/intel/libva.git
    source-tag: 2.22.0
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment: *build-environment
    build-packages:
      - libdrm-dev
      - libwayland-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-dri3-dev
      - vulkan-sdk
    stage-packages:
      - libgl1
      - libglvnd0
      - libglx0

  sdl:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL.git
    source-branch: SDL2
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-alsa
      - --disable-arts
      - --disable-esd
      - --disable-nas
      - --disable-oss
      - --disable-rpath
      - --disable-sndio
      - --disable-static
    build-environment: *build-environment
    after:
      - libdecor
    build-packages:
      - libasound2-dev
      - libdbus-1-dev
      - libdrm-dev
      - libgbm-dev
      - libibus-1.0-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsndio-dev
      - libwayland-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - pkg-config
      - wayland-protocols
    stage-packages:
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0

  sdl-ttf:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL_ttf.git
    source-tag: release-2.22.0
    autotools-configure-parameters:
      - --disable-static
      - --prefix=/usr
    build-environment: *build-environment
    after:
      - sdl
    build-packages:
      - libfreetype-dev
      - pkg-config
    stage-packages:
      - libfreetype6
      - libpng16-16

  libdecor:
    plugin: meson
    source: https://gitlab.freedesktop.org/libdecor/libdecor.git
    source-tag: 0.2.2
    meson-parameters:
      - -Ddemo=false
      - -Dprefix=/usr
    build-environment: *build-environment
    build-packages:
      - libcairo2-dev
      - libgtk-3-dev
      - librust-pangocairo-dev
    stage-packages:
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libxcb-render0
      - libxcb-shm0
      - libxrender1
    after:
      - meson-deps

  dav1d:
    plugin: meson
    source: https://code.videolan.org/videolan/dav1d.git
    source-tag: 1.5.2
    meson-parameters:
      - -Denable_tools=false
      - -Denable_tests=false
      - -Dprefix=/usr
    build-environment: *build-environment
    after:
      - meson-deps

  libplacebo:
    plugin: meson
    source: https://github.com/haasn/libplacebo.git
    source-commit: 1dcaea8b601aa969ffd5bfa70088957ce3eaa273
    meson-parameters:
      - -Ddemos=false
      - -Dvulkan=enabled
      - -Dopengl=disabled
      - -Dshaderc=enabled
      - -Dprefix=/usr
    build-environment: *build-environment
    build-packages:
      - vulkan-sdk
    stage-packages:
      - shaderc
    after:
      - meson-deps

  meson-deps:
    plugin: nil
    build-packages:
      - pipx
    override-pull: |
      PIPX_BIN_DIR=/usr/bin/ PIPX_HOME=/usr/local/lib/pipx/ pipx install meson
    stage-packages:
      - ninja-build

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make

  fix-vulkan-drivers-path:
    after:
      - moonlight-qt
    plugin: nil
    override-prime: |
      sed -i s%/usr/lib/x86_64-linux-gnu/%% $CRAFT_PRIME/usr/share/vulkan/icd.d/*.json

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
    override-prime: |
      set -eux
      for snap in "core22"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
