name: moonlight
base: core20
adopt-info: moonlight-qt
grade: devel
confinement: strict
license: GPL-3.0+

apps:
  moonlight:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
  vainfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/vainfo
    plugs: *plugs
  vdpauinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/vdpauinfo
    plugs: *plugs
  eglinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/eglinfo
    plugs: *plugs
  glxinfo:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/glxinfo
    plugs: *plugs

parts:
  va-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages: [mesa-utils, mesa-utils-extra, vainfo, vdpauinfo]

  moonlight-qt:
    plugin: make
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-branch: master
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    override-build: |
      snapcraftctl set-version $(git describe --tags --long | sed "s/^v//")
      qmake \
        INCLUDEPATH+={$SNAPCRAFT_PART_INSTALL,$SNAPCRAFT_STAGE}/usr/include \
        LIBS+=-L{$SNAPCRAFT_PART_INSTALL,$SNAPCRAFT_STAGE}{/usr,}/lib{/$SNAPCRAFT_ARCH_TRIPLET,} \
        PREFIX=/usr
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      make install INSTALL_ROOT=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libopus-dev
      - libqt5svg5-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libssl-dev
      - libavcodec-dev
      - libva-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-default
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - intel-media-va-driver-non-free
      - libasound2
      - libasyncns0
      - libdrm2
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libsndfile1
      - libsndio7.0
      - libva-drm2
      - libva-wayland2
      - libva-x11-2
      - libvdpau-va-gl1
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all
    after:
      - desktop-qt5
      - ffmpeg

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-branch: sdk/8.1

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-branch: master
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-pic
      - --enable-shared
      - --disable-static
      - --disable-all
      - --enable-avcodec
      - --enable-nvdec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_vdpau
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=hevc_nvdec
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
    after: [ffnvcodec]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
      - va-wrapper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
    override-prime: |
      set -eux
      for snap in "core20"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
