name: moonlight
base: core20
adopt-info: moonlight-qt
grade: stable
confinement: strict
license: GPL-3.0+
icon: moonlight.svg
compression: lzo

apps:
  moonlight:
    command-chain: &command-chain
      - bin/desktop-launch
      - env-wrapper
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11

parts:
  env-wrapper:
    plugin: dump
    source: snap/local/

  moonlight-qt:
    plugin: qmake
    qmake-parameters:
      - PREFIX=/usr
      # Need to manually set this for the linker to find libdecor when linking SDL...
      - QMAKE_LFLAGS+=-Wl,-rpath-link,${SNAPCRAFT_STAGE}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-tag: v3.2.0
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags | sed "s/^v//")
    after:
      - desktop-qt5
      - ffmpeg
      - sdl
      - sdl-ttf
      - moonlight-qt-deps

  moonlight-qt-deps:
    plugin: nil
    build-packages:
      - libopus-dev
      - libqt5svg5-dev
      - libssl-dev
      - libavcodec-dev
      - libva-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-default
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - intel-media-va-driver-non-free
      - libasound2
      - libasyncns0
      - libdrm2
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsndfile1
      - libsndio7.0
      - libva-drm2
      - libva-wayland2
      - libva-x11-2
      - libvdpau-va-gl1
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-tag: n8.1.24.13
    make-parameters: [PREFIX=/usr]

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-tag: n5.0
    autotools-configure-parameters:
      - --disable-all
      - --disable-static
      - --enable-avcodec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_nvdec
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=hevc_vdpau
      - --enable-nvdec
      - --enable-pic
      - --enable-shared
      - --prefix=/usr
    after:
      - ffnvcodec
      - sdl
      - ffmpeg-deps

  ffmpeg-deps:
    plugin: nil
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3

  sdl:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL.git
    source-commit: a0e3c884d4519d4ae02f5c22c7557759eaea60ca
    override-build: |
      # Prevent SIGSEGV by manually reverting two input related SDL commits (?)
      git revert 62a562dea20728726a497b4af49d591a2fa385de 531d83bf6a140fcb5a858c9f23c76198016db869 --no-edit
      snapcraftctl build
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-alsa
      - --disable-arts
      - --disable-esd
      - --disable-libudev
      - --disable-nas
      - --disable-oss
      - --disable-rpath
      - --disable-sndio
      - --disable-static
    after:
      - libdecor
      - sdl-deps

  sdl-deps:
    plugin: nil
    build-packages:
      - libasound2-dev
      - libdbus-1-dev
      - libdrm-dev
      - libgbm-dev
      - libibus-1.0-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsndio-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - pkg-config
      - wayland-protocols
    stage-packages:
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0

  sdl-ttf:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL_ttf.git
    source-tag: release-2.0.15
    override-build: |
      ./autogen.sh
      snapcraftctl build
    autotools-configure-parameters:
      - --disable-static
      - --prefix=/usr
    after:
      - sdl
      - sdl-ttf-deps

  sdl-ttf-deps:
    plugin: nil
    build-packages:
      - libfreetype-dev
      - pkg-config
    stage-packages:
      - libfreetype6
      - libpng16-16

  libdecor:
    plugin: meson
    source: https://gitlab.gnome.org/jadahl/libdecor.git
    source-commit: a5e1d87dc80d8a71076f64d0fc33f38cc0fc205a
    meson-parameters:
      - -Ddemo=false
      - -Dprefix=/usr
    after:
      - libdecor-deps

  libdecor-deps:
    plugin: nil
    build-packages:
      - libcairo2-dev
      - librust-pangocairo-dev
    stage-packages:
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libxcb-render0
      - libxcb-shm0
      - libxrender1

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
      - env-wrapper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
    override-prime: |
      set -eux
      for snap in "core20"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
