name: moonlight
base: core18
title: Moonlight
version: master
version-script: git -C parts/moonlight-qt/build/ describe --tags --long | sed "s/^v//"
adopt-info: moonlight-qt
grade: devel
confinement: strict
icon: moonlight.png
license: GPL-3.0+

apps:
  moonlight:
    command: desktop-launch $SNAP/va-wrapper $SNAP/usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
  vainfo:
    command: desktop-launch $SNAP/va-wrapper $SNAP/usr/bin/vainfo
    plugs: *plugs
  vdpauinfo:
    command: desktop-launch $SNAP/va-wrapper $SNAP/usr/bin/vdpauinfo
    plugs: *plugs

parts:
  va-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages: [mesa-utils, vainfo, vdpauinfo]

  moonlight-qt:
    plugin: qmake
    qt-version: qt5
    options: [PREFIX=/usr]
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-branch: master
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    build-packages:
      - qtbase5-dev
      - qtquickcontrols2-5-dev
      - libqt5svg5-dev
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libxkbcommon-dev
      - wayland-protocols
      - libopus-dev
      - libva-dev
      - libvdpau-dev
      - libsdl2-dev
      - qtdeclarative5-dev
      - libssl-dev
      - libsdl2-ttf-dev
    stage-packages:
      - qml-module-qtquick2
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - libvdpau-va-gl1
      - i965-va-driver
      - vdpau-va-driver
      - va-driver-all
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva-wayland2
      - libvdpau1
      - libasound2
      - libasyncns0
      - libblkid1
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libmount1
      - libogg0
      - libopus0
      - libpcre3
      - libpulse0
      - libqt5svg5
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - libselinux1
      - libsndfile1
      - libsndio6.1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libudev1
      - libuuid1
      - libvorbis0a
      - libvorbisenc2
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libwrap0
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxss1
      - zlib1g
    after:
      - desktop-qt5
      - ffmpeg

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-branch: master
    configflags:
      - --prefix=/usr
      - --enable-pic
      - --enable-shared
      - --disable-static
      - --disable-all
      - --enable-avcodec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_vdpau
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: stable
    source-subdir: qt
    plugin: make

  fix-icon:
    plugin: nil
    override-build:
      sed -i 's|Icon=moonlight|Icon=/usr/share/icons/hicolor/scalable/apps/moonlight.svg|' $SNAPCRAFT_STAGE/usr/share/applications/com.moonlight_stream.Moonlight.desktop
    after: [moonlight-qt]
