name: moonlight
base: core22
adopt-info: moonlight-qt
grade: stable
confinement: strict
license: GPL-3.0+
icon: moonlight.svg
compression: lzo

apps:
  moonlight:
    command-chain: [bin/desktop-launch]
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    environment:
      LIBDECOR_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libdecor/plugins-1
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11

parts:
  moonlight-qt:
    plugin: make
    build-environment: &build-environment
      - CFLAGS: -O2 -g -pipe
      - CXXFLAGS: -O2 -g -pipe
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-tag: v4.3.0
    parse-info:
      - app/deploy/linux/com.moonlight_stream.Moonlight.appdata.xml
      - usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | sed "s/^v//")
    override-build: |
      qmake PREFIX=/usr
      craftctl default
      make install INSTALL_ROOT="${CRAFT_PART_INSTALL}"
    after:
      - desktop-qt5
      - ffmpeg
      - libva
      - sdl
      - sdl-ttf
    build-packages:
      - libopus-dev
      - libqt5svg5-dev
      - libssl-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - intel-media-va-driver-non-free
      - libasound2
      - libasyncns0
      - libdrm2
      - libegl1-mesa-dev
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsndfile1
      - libsndio7.0
      - libvdpau-va-gl1
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-tag: n8.1.24.13
    make-parameters: [PREFIX=/usr]
    build-environment: *build-environment

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-tag: n5.1
    autotools-configure-parameters:
      - --disable-all
      - --disable-static
      - --enable-avcodec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_nvdec
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=hevc_vdpau
      - --enable-nvdec
      - --enable-pic
      - --enable-shared
      - --prefix=/usr
    build-environment: *build-environment
    after:
      - ffnvcodec
      - libva
      - sdl
    build-packages:
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3

  libva:
    plugin: autotools
    source: https://github.com/intel/libva.git
    source-tag: 2.16.0
    autotools-configure-parameters:
      - --prefix=/usr
    build-environment: *build-environment
    build-packages:
      - libdrm-dev
      - libwayland-dev
      - libx11-dev
    stage-packages:
      - libgl1
      - libglvnd0
      - libglx0

  sdl:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL.git
    source-commit: c6c688ab0184234f3ea8240be80df405fdda5b9a
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-alsa
      - --disable-arts
      - --disable-esd
      - --disable-libudev
      - --disable-nas
      - --disable-oss
      - --disable-rpath
      - --disable-sndio
      - --disable-static
    build-environment: *build-environment
    after:
      - libdecor
    build-packages:
      - libasound2-dev
      - libdbus-1-dev
      - libdrm-dev
      - libgbm-dev
      - libibus-1.0-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsndio-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - pkg-config
      - wayland-protocols
    stage-packages:
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0

  sdl-ttf:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL_ttf.git
    source-tag: release-2.20.1
    override-build: |
      ./autogen.sh
      craftctl default
    autotools-configure-parameters:
      - --disable-static
      - --prefix=/usr
    build-environment: *build-environment
    after:
      - sdl
    build-packages:
      - libfreetype-dev
      - pkg-config
    stage-packages:
      - libfreetype6
      - libpng16-16

  libdecor:
    plugin: meson
    source: https://gitlab.gnome.org/jadahl/libdecor.git
    source-commit: 5e58ec6258a45d3149f83e28acb997962cbfc170
    meson-parameters:
      - -Ddemo=false
      - -Dprefix=/usr
    build-environment: *build-environment
    build-packages:
      - libcairo2-dev
      - librust-pangocairo-dev
      - meson
      - ninja-build
    stage-packages:
      - libcairo2
      - libdatrie1
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libxcb-render0
      - libxcb-shm0
      - libxrender1

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core20
    override-prime: |
      set -eux
      for snap in "core22"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
