name: moonlight
base: core18
adopt-info: moonlight-qt
grade: stable
confinement: strict
license: GPL-3.0+
icon: moonlight.svg
compression: lzo

apps:
  moonlight:
    command-chain: [bin/desktop-launch, va-wrapper]
    command: usr/bin/moonlight
    common-id: com.moonlight_stream.Moonlight
    plugs: &plugs
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - joystick
      - network
      - opengl
      - screen-inhibit-control
      - wayland
      - x11

parts:
  va-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages: [mesa-utils]

  moonlight-qt:
    plugin: qmake
    qt-version: qt5
    options: [PREFIX=/usr]
    source: https://github.com/moonlight-stream/moonlight-qt.git
    source-tag: v3.1.2
    parse-info: [usr/share/metainfo/com.moonlight_stream.Moonlight.appdata.xml]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags | sed "s/^v//")
    build-packages:
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libopus-dev
      - libqt5svg5-dev
      - libssl-dev
      - libavcodec-dev
      - libva-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - qt5-default
      - qt5-qmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - wayland-protocols
    stage-packages:
      - i965-va-driver
      - libasound2
      - libasyncns0
      - libdrm2
      - libflac8
      - libogg0
      - libopus0
      - libpulse0
      - libqt5svg5
      - libqt5widgets5
      - libsndfile1
      - libsndio6.1
      - libva-drm2
      - libva-wayland2
      - libva-x11-2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - qml-module-qtquick-controls2
      - qml-module-qtquick-layouts
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - qtwayland5
      - va-driver-all
    after:
      - desktop-qt5
      - ffmpeg
      - sdl
      - sdl-ttf

  ffnvcodec:
    plugin: make
    source: https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
    source-branch: sdk/8.1
    make-parameters: [PREFIX=/usr]

  ffmpeg:
    plugin: autotools
    source: https://git.ffmpeg.org/ffmpeg.git
    source-tag: n4.3.1
    configflags:
      - --disable-all
      - --disable-static
      - --enable-avcodec
      - --enable-decoder=h264
      - --enable-decoder=hevc
      - --enable-hwaccel=h264_nvdec
      - --enable-hwaccel=h264_vaapi
      - --enable-hwaccel=h264_vdpau
      - --enable-hwaccel=hevc_nvdec
      - --enable-hwaccel=hevc_vaapi
      - --enable-hwaccel=hevc_vdpau
      - --enable-nvdec
      - --enable-pic
      - --enable-shared
      - --prefix=/usr
    build-packages:
      - libva-dev
      - libvdpau-dev
      - libx265-dev
      - nasm
    stage-packages:
      - libdrm2
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
    after:
      - ffnvcodec
      - sdl

  sdl:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL.git
    source-commit: dfa64eadd38a6a8125290dcf121f1bc285e98dad
    configflags:
      - --prefix=/usr
      - --disable-alsa
      - --disable-arts
      - --disable-esd
      - --disable-libudev
      - --disable-nas
      - --disable-oss
      - --disable-rpath
      - --disable-sndio
      - --disable-static
      - --enable-sdl-dlopen
      - --enable-video-kmsdrm
      - --enable-video-wayland
      - --enable-wayland-shared=no
    build-packages:
      - libasound2-dev
      - libdbus-1-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libgbm-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libglu1-mesa-dev
      - libibus-1.0-dev
      - libpulse-dev
      - libsamplerate0-dev
      - libsndio-dev
      - libvulkan-dev
      - libwayland-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxt-dev
      - libxv-dev
      - libxxf86vm-dev
      - pkg-config
      - wayland-protocols
    stage-packages:
      - libwayland-cursor0
      - libwayland-egl1
      - libxkbcommon0

  sdl-ttf:
    plugin: autotools
    source: https://github.com/libsdl-org/SDL_ttf.git
    source-tag: release-2.0.15
    override-build: |
      ./autogen.sh
      snapcraftctl build
    configflags:
      - --disable-static
      - --prefix=/usr
    build-packages:
      - libfreetype6-dev
      - pkg-config
    stage-packages:
      - libfreetype6
      - libpng16-16
    after:
      - sdl

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: master
    source-subdir: qt
    plugin: make
    after: [kde-neon-ppa]

  kde-neon-ppa:
    plugin: nil
    override-pull: |
      echo "deb http://archive.neon.kde.org/release bionic main" | tee /etc/apt/sources.list.d/kde-neon.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E6D4736255751E5D
      apt update
      apt upgrade -yy
    build-packages:
      - dirmngr

  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - moonlight-qt
      - va-wrapper
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
    override-prime: |
      set -eux
      for snap in "core18"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
