name: EDGE automatic builds
on:
  push:
    branches: [master]
  workflow_run:
    workflows: ["Check upstream activity"]
    branches: [master]
    types: [completed]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
