name: Build, upload & release to EDGE
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1.0.8
        id: build
    outputs:
      snap: ${{ steps.build.outputs.snap }}
  upload:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ needs.build.outputs.snap }}
  release:
    runs-on: ubuntu-20.04
    needs: [build, upload]
    steps:
      - uses: snapcore/action-publish@v1.0.2
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ needs.build.outputs.snap }}
          release: edge
