name: Build, upload & release to EDGE
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.build.outputs.snap }}
    outputs:
      snap: ${{ steps.build.outputs.snap }}
      
  publish:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snap    
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ needs.build.outputs.snap }}
          release: edge
