name: Auto EDGE amd64 builds from master (unstable)
on:
  push:
    branches: [master]
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
  
jobs:
  get-latest-upstream-commit:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.fetch-latest-commit.outputs.sha }}
    steps:
      - id: fetch-latest-commit
        run: |
          SHA=$(curl -s -f https://api.github.com/repos/moonlight-stream/moonlight-qt/commits/master | jq -r .sha)
          echo "SHA: $SHA"
          echo "::set-output name=sha::$SHA"

  get-edge-snap-metadata:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.fetch-edge-snap-metadata.outputs.version }}
    steps:
      - id: fetch-edge-snap-metadata
        run: |
          VERSION=$(curl -s -f -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/moonlight" \
          | jq -r '."channel-map"[] | select(.channel.architecture=="amd64" and .channel.track=="latest" and .channel.name=="edge") | .version' \
          | grep -oP '[0-9\.]+-[0-9]+-g\K[0-9a-f0]+')
          echo "VERSION: $VERSION"
          echo "::set-output name=version::$VERSION"
  
  build-and-publish:
    runs-on: ubuntu-20.04
    needs: [get-latest-upstream-commit, get-edge-snap-metadata]
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && !startswith(needs.get-latest-upstream-commit.outputs.sha, needs.get-edge-snap-metadata.outputs.version))
    steps:
      - env:
          LATEST_UPSTREAM_COMMIT: ${{ needs.get-latest-upstream-commit.outputs.sha }}
          EDGE_SNAP_VERSION: ${{ needs.get-edge-snap-metadata.outputs.version }}
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "LATEST_UPSTREAM_COMMIT: $LATEST_UPSTREAM_COMMIT"
          echo "EDGE_SNAP_VERSION: $EDGE_SNAP_VERSION"
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge

