name: CANDIDATE amd64 builds (stable)
on:
  push:
    branches: [candidate]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN_CANDIDATE }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: candidate
