name: EDGE automatic builds
on:
  push:
    branches: [master]
  schedule:
    - cron: '42 * * * *'
  workflow_dispatch:
  
jobs:
  latest-commit-datetime:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install curl dateutils jq
          LAST_COMMIT_DATETIME=$(curl -s https://api.github.com/repos/moonlight-stream/moonlight-qt/commits/master | jq -r .commit.author.date)
          echo LAST_COMMIT_DATETIME=$LAST_COMMIT_DATETIME
          SECONDS_SINCE_COMMIT=$(dateutils.ddiff "$LAST_COMMIT_DATETIME" now -f %S)
          echo SECONDS_SINCE_COMMIT=$SECONDS_SINCE_COMMIT
          echo "::set-output name=age::$SECONDS_SINCE_COMMIT"
  build-and-publish:
    runs-on: ubuntu-20.04
    needs: latest-commit-datetime
    if: |
      ${{ 
        github.event_name == 'push'
        || github.event_name == 'workflow_dispatch'
      }}
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
