name: EDGE amd64 builds from master (unstable)
on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-edge-build-event]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-channel: candidate
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN_EDGE }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
