name: EDGE amd64 builds from master (unstable)
on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-edge-build-event]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-channel: edge
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_EDGE }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge

