name: CANDIDATE amd64 builds (stable)
on:
  push:
    branches: [candidate]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: snapcore/action-build@v1.0.9
        id: build
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN_CANDIDATE }}
          snap: ${{ steps.build.outputs.snap }}
          release: candidate
