name: Check upstream activity
on:
  schedule:
    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  check-latest-commit-datetime:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install curl dateutils jq
          LAST_COMMIT_DATETIME=$(curl -s https://api.github.com/repos/moonlight-stream/moonlight-qt/commits/master | jq -r .commit.author.date)
          echo LAST_COMMIT_DATETIME=$LAST_COMMIT_DATETIME
          SECONDS_SINCE_COMMIT=$(dateutils.ddiff "$LAST_COMMIT_DATETIME" now -f %S)
          echo SECONDS_SINCE_COMMIT=$SECONDS_SINCE_COMMIT
          [[ "$SECONDS_SINCE_COMMIT" < 3600 ]]
