name: Check upstream activity
on:
  schedule:
    - cron: '42 * * * *'
  workflow_dispatch:

jobs:
  check-latest-commit-datetime:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install dateutils
          LAST_COMMIT_DATETIME=$(curl -s https://api.github.com/repos/moonlight-stream/moonlight-qt/commits/master | jq -r .commit.author.date)
          SECONDS_SINCE_COMMIT=$(dateutils.ddiff "$LAST_COMMIT_DATETIME" now -f %S)
          [[ "$SECONDS_SINCE_COMMIT" < 3600 ]]
